"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 01:04:39.703525
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('name', name=op.f('uq_cities_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_users_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('max_user_id', name=op.f('uq_users_max_user_id'))
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_venues_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('city_id', 'name', name='uq_venues_city_name')
    )
    op.create_index(op.f('ix_venues_city_id'), 'venues', ['city_id'], unique=False)
    op.create_table('dialog_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('shown_event_ids', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False),
    sa.Column('first_recommended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dialog_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialog_sessions'))
    )
    op.create_index('uq_dialog_sessions_active_user', 'dialog_sessions', ['user_id'], unique=True, postgresql_where='is_active')
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=False),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('age_limit', sa.SmallInteger(), nullable=False),
    sa.Column('pushkin_card', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=30)), server_default='{}', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ticket_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', name='eventstatus', native_enum=False, length=24), nullable=False),
    sa.Column('is_test_data', sa.Boolean(), nullable=False),
    sa.Column('data_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_max IS NULL OR price_max >= price_min', name=op.f('ck_events_price_range')),
    sa.CheckConstraint('price_min >= 0', name=op.f('ck_events_price_min_non_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_events_category_id_categories')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_events_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('source', 'external_id', name='uq_events_source_external_id')
    )
    op.create_index(op.f('ix_events_category_id'), 'events', ['category_id'], unique=False)
    op.create_index('ix_events_status_starts_at', 'events', ['status', 'starts_at'], unique=False)
    op.create_index('ix_events_tags', 'events', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_events_venue_id'), 'events', ['venue_id'], unique=False)
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_polls_creator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polls'))
    )
    op.create_table('user_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_user_interests_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('pk_user_interests'))
    )
    op.create_table('dialog_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='messagerole', native_enum=False, length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['dialog_sessions.id'], name=op.f('fk_dialog_messages_session_id_dialog_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialog_messages'))
    )
    op.create_index(op.f('ix_dialog_messages_session_id'), 'dialog_messages', ['session_id'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_favorites_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name=op.f('pk_favorites'))
    )
    op.create_table('interactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('shown', 'opened', 'favorited', 'reminder_set', 'ticket_click', 'poll_created', 'poll_voted', name='interactionkind', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_interactions_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['dialog_sessions.id'], name=op.f('fk_interactions_session_id_dialog_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interactions'))
    )
    op.create_index('ix_interactions_kind_created_at', 'interactions', ['kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_poll_options_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_options_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_options')),
    sa.UniqueConstraint('poll_id', 'event_id', name='uq_poll_options_poll_event'),
    sa.UniqueConstraint('poll_id', 'id', name='uq_poll_options_poll_id_id')
    )
    op.create_table('reminders',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_reminders_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name=op.f('pk_reminders'))
    )
    op.create_index('ix_reminders_due', 'reminders', ['remind_at'], unique=False, postgresql_where='sent_at IS NULL')
    op.create_table('poll_votes',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poll_id', 'option_id'], ['poll_options.poll_id', 'poll_options.id'], name='fk_poll_votes_option_in_poll', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_votes_poll_id_polls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_poll_votes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poll_id', 'user_id', name=op.f('pk_poll_votes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_votes')
    op.drop_index('ix_reminders_due', table_name='reminders', postgresql_where='sent_at IS NULL')
    op.drop_table('reminders')
    op.drop_table('poll_options')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index('ix_interactions_kind_created_at', table_name='interactions')
    op.drop_table('interactions')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_dialog_messages_session_id'), table_name='dialog_messages')
    op.drop_table('dialog_messages')
    op.drop_table('user_interests')
    op.drop_table('polls')
    op.drop_index(op.f('ix_events_venue_id'), table_name='events')
    op.drop_index('ix_events_tags', table_name='events', postgresql_using='gin')
    op.drop_index('ix_events_status_starts_at', table_name='events')
    op.drop_index(op.f('ix_events_category_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('uq_dialog_sessions_active_user', table_name='dialog_sessions', postgresql_where='is_active')
    op.drop_table('dialog_sessions')
    op.drop_index(op.f('ix_venues_city_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_table('users')
    op.drop_table('cities')
    op.drop_table('categories')
    # ### end Alembic commands ###
